---
fixtures:
  repositories:
    auditd: https://github.com/simp/pupmod-simp-auditd
    augeasproviders_core: https://github.com/simp/augeasproviders_core
    augeasproviders_grub: https://github.com/simp/augeasproviders_grub
    concat:
      # master is beyond 4.1.1, but has breaking changes to
      # how fragments are ordered (MODULES-6625)
      repo: https://github.com/simp/puppetlabs-concat
      ref: 4.1.1
    iptables: https://github.com/simp/pupmod-simp-iptables
    simplib: https://github.com/simp/pupmod-simp-simplib
    stdlib: https://github.com/simp/puppetlabs-stdlib
  symlinks:
    ntpd: "#{source_dir}"
