---
fixtures:
  repositories:
    auditd: https://github.com/simp/pupmod-simp-auditd
    augeasproviders_core: https://github.com/simp/augeasproviders_core
    augeasproviders_grub: https://github.com/simp/augeasproviders_grub
    concat:
      # master is at 4.0.1, but we are bound to < 4.0.0 in our metadata.json
      repo: https://github.com/simp/puppetlabs-concat
      ref: 3.0.0
    iptables: https://github.com/simp/pupmod-simp-iptables
    logrotate: https://github.com/simp/pupmod-simp-logrotate
    pki: https://github.com/simp/pupmod-simp-pki
    rsyslog: https://github.com/simp/pupmod-simp-rsyslog
    simplib: https://github.com/simp/pupmod-simp-simplib
    stdlib: https://github.com/simp/puppetlabs-stdlib
  symlinks:
    ntpd: "#{source_dir}"
